//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace UnitPricing.wsJobPricer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrderRequiredOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPriceRequiredOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::UnitPricing.Properties.Settings.Default.UnitPricing_wsJobPricer_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrderRequiredCompletedEventHandler GetOrderRequiredCompleted;
        
        /// <remarks/>
        public event GetPriceRequiredCompletedEventHandler GetPriceRequiredCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderRequired", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public assoc_category[] GetOrderRequired(int prod_family) {
            object[] results = this.Invoke("GetOrderRequired", new object[] {
                        prod_family});
            return ((assoc_category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderRequiredAsync(int prod_family) {
            this.GetOrderRequiredAsync(prod_family, null);
        }
        
        /// <remarks/>
        public void GetOrderRequiredAsync(int prod_family, object userState) {
            if ((this.GetOrderRequiredOperationCompleted == null)) {
                this.GetOrderRequiredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderRequiredOperationCompleted);
            }
            this.InvokeAsync("GetOrderRequired", new object[] {
                        prod_family}, this.GetOrderRequiredOperationCompleted, userState);
        }
        
        private void OnGetOrderRequiredOperationCompleted(object arg) {
            if ((this.GetOrderRequiredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderRequiredCompleted(this, new GetOrderRequiredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPriceRequired", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public assoc_category[] GetPriceRequired(int prod_family) {
            object[] results = this.Invoke("GetPriceRequired", new object[] {
                        prod_family});
            return ((assoc_category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceRequiredAsync(int prod_family) {
            this.GetPriceRequiredAsync(prod_family, null);
        }
        
        /// <remarks/>
        public void GetPriceRequiredAsync(int prod_family, object userState) {
            if ((this.GetPriceRequiredOperationCompleted == null)) {
                this.GetPriceRequiredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceRequiredOperationCompleted);
            }
            this.InvokeAsync("GetPriceRequired", new object[] {
                        prod_family}, this.GetPriceRequiredOperationCompleted, userState);
        }
        
        private void OnGetPriceRequiredOperationCompleted(object arg) {
            if ((this.GetPriceRequiredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceRequiredCompleted(this, new GetPriceRequiredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class assoc_category {
        
        private long vpcID1Field;
        
        private long vpcID2Field;
        
        /// <remarks/>
        public long vpcID1 {
            get {
                return this.vpcID1Field;
            }
            set {
                this.vpcID1Field = value;
            }
        }
        
        /// <remarks/>
        public long vpcID2 {
            get {
                return this.vpcID2Field;
            }
            set {
                this.vpcID2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetOrderRequiredCompletedEventHandler(object sender, GetOrderRequiredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderRequiredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderRequiredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public assoc_category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((assoc_category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPriceRequiredCompletedEventHandler(object sender, GetPriceRequiredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceRequiredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceRequiredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public assoc_category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((assoc_category[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591